### Site Settings ###
title               : Dinoroco Studios
description         : A Spanish software company founded in 2022, dedicated to crafting apps for iOS.
baseurl             : ""
repository          : Dinoroco-Studios/Dinoroco-Studios.github.io


### Plugins ###
plugins:
  - jemoji


### Author Info ###
author:
  name              : Dinoroco Studios
  email             : info@dinoroco.com
  github            : Dinoroco-Studios
  linkedin          : dinoroco-studios
  twitter           : DinorocoStudios
  image             : /assets/logo/logo1024x1024.webp


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - "*.log"
